In [2]:
import torchvision

In [5]:
model = torchvision.models.get_model("resnet18", weights=None, num_classes=200)

In [1]:
round(4.62367573, 5)

4.62368

In [1]:
import ot

In [6]:
ot.unif(5)

In [7]:
import numpy as np
a = np.ones(5) / 5
a

AssertionError: 

In [4]:
a.shape

AssertionError: 

In [8]:
b=np.expand_dims(a, axis=0)

In [12]:
print(b)

[[0.2 0.2 0.2 0.2 0.2]]


In [51]:
import torch

In [44]:
labels = torch.tensor([0.3, 0.2, 2, 0.5, 2, 0.4])
labels

tensor([0.3000, 0.2000, 2.0000, 0.5000, 2.0000, 0.4000])

In [47]:
indices = (labels == 0.5)
indices

tensor([False, False, False,  True, False, False])

In [48]:
indices = indices.nonzero(as_tuple=False).squeeze(1)
indices

tensor([3])

In [49]:
b = torch.randn(6,4)
b

tensor([[-1.0669, -0.6981,  1.1967,  1.2448],
        [-2.4303, -0.4821, -0.3298, -0.5869],
        [ 0.8037, -0.9979,  0.8632,  0.3956],
        [-0.1665,  1.4555,  1.0579,  2.3945],
        [-0.6917, -0.5217, -0.4076,  0.7410],
        [-0.1301,  0.2558,  0.7024,  0.4193]])

In [50]:
b[indices]

tensor([[-0.1665,  1.4555,  1.0579,  2.3945]])

In [69]:
x = torch.tensor([[5.,12.],[3.,4.]])
x

tensor([[ 5., 12.],
        [ 3.,  4.]])

In [70]:
torch.norm(x, dim=1)

tensor([13.,  5.])

In [57]:
x.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

In [59]:
torch.tensor(2.6)

tensor(2.6000)

In [2]:
14 // 5

2

In [5]:
5 // 3

1

In [9]:
199 // 100

1

In [8]:
200 // 1

200

In [13]:
import torch
import numpy as np

In [18]:
a = torch.LongTensor(np.arange(5, 10))
a

tensor([5, 6, 7, 8, 9])

In [23]:
b = a.repeat_interleave(3)
b

tensor([5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9])

In [26]:
b.reshape(5, 3)

tensor([[5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [27]:
b.reshape(3, 5)

tensor([[5, 5, 5, 6, 6],
        [6, 7, 7, 7, 8],
        [8, 8, 9, 9, 9]])

In [30]:
19 % 19

0

In [7]:
import numpy as np
import torch

In [3]:
k = 10

array([1., 1., 1., 1., 1.])

In [11]:
a = torch.tensor(np.stack([np.ones(4) / k, np.zeros((3, k)) / k]))

In [14]:
a

'4/5/3'

In [4]:
10 // 11

0

In [1]:
import numpy as np

In [2]:
np.std([64.4, 64.1])

0.15000000000000568

In [1]:
import torch

In [2]:
data = torch.load('tinyimagenet.pt')

In [3]:
data

{'images_train': tensor([[[[255, 255, 246,  ..., 208, 207, 125],
           [255, 255, 246,  ..., 203, 200, 121],
           [255, 255, 255,  ..., 207, 200, 119],
           ...,
           [ 94,  93,  93,  ...,  85,  78,  94],
           [ 89,  88,  87,  ...,  86,  77,  87],
           [ 91,  91,  91,  ...,  96,  77,  72]],
 
          [[137, 139, 148,  ..., 237, 241, 164],
           [124, 128, 137,  ..., 232, 235, 160],
           [124, 127, 134,  ..., 233, 235, 156],
           ...,
           [122, 119, 116,  ...,  74,  67,  83],
           [118, 116, 113,  ...,  75,  66,  76],
           [120, 119, 117,  ...,  85,  66,  61]],
 
          [[192, 192, 197,  ..., 235, 240, 161],
           [189, 189, 194,  ..., 230, 231, 157],
           [201, 201, 203,  ..., 230, 229, 149],
           ...,
           [ 71,  71,  70,  ...,  56,  49,  65],
           [ 64,  65,  66,  ...,  57,  48,  58],
           [ 66,  68,  70,  ...,  67,  48,  43]]],
 
 
         [[[ 20,  19,  22,  ...,  47,  51,

In [4]:
data.keys()

dict_keys(['images_train', 'images_val', 'images_test', 'labels_train', 'labels_val', 'labels_test', 'fnames_train', 'fnames_val', 'fnames_test', 'clsnames_train', 'clsnames_val', 'clsnames_test', 'classes'])

In [6]:
data['images_val'].shape

torch.Size([10000, 3, 64, 64])

In [8]:
data['labels_train']

tensor([  0,   0,   0,  ..., 199, 199, 199])

In [10]:
data['labels_test'].shape

torch.Size([10000])